export { default as Navbar } from "./navbar"
export { default as Hero } from "./hero"
export { default as About } from "./about"
export { default as Skills } from "./skills"
export { default as Projects } from "./projects"
export { default as Award } from "./award"
export { default as Footer } from "./footer"